baseURL = "https://jonny-jackson.com/"
languageCode = 'en-us'
title = 'Jonny Jackson'
theme = 'PaperMod'

[pagination]
  pagerSize = 50 

[params]
  env = "production"  # change to "development" if needed
  title = "Jonny Jackson"
  description = "Jonny Jackson's portfolio and coding projects"
  keywords = ["software", "portfolio", "developer", "Jonny Jackson", "coding", "programmer"]
  author = "Jonny Jackson"
  DateFormat = "Jan 2006"
  defaultTheme = "auto"  # dark, light, or auto
  disableThemeToggle = false

  ShowReadingTime = false
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false

  [params.homeInfoParams]
    Title = "Jonny Jackson"
    Content = "I love creating things. Full-Stack Software Engineer, mainly with experience in Next.js and React Native/Expo."

  [params.assets]
    disableHLJS = false
    disableFingerprinting = false
    favicon = "favicons/favicon.ico"
    apple_touch_icon = "favicons/apple-touch-icon.png"
    safari_pinned_tab = "favicons/favicon.svg"

  [params.analytics.google]
    id = "G-RR0J5V80WV"

  [params.search]
    enabled = true
    type = "lunr"  

  [[params.socialIcons]]
    name = "email"
    url = "mailto:jrsjackson26@gmail.com"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jonnyjackson26"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/channel/UCUPGPAKijHmEutSMKr6cnwg"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jonny-jackson/"
    


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    pre = "🏠 "  # emoji icon

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 2
    pre = "📦 "

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
    pre = "🏷️ "

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 4
    pre = "🔍 "

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]  # JSON is needed for Lunr.js search

