backend:
  name: git-gateway
  branch: main # or "master" if that's your repo branch

media_folder: "static/uploads" # Where uploaded files are stored
public_folder: "/uploads" # How Hugo will reference those files

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter" # Hugo front matter format

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - {
              label: "Image URL",
              name: "image",
              widget: "string",
              required: false,
            }
          - {
              label: "Alt Text",
              name: "alt",
              widget: "string",
              required: false,
            }
          - {
              label: "Hidden in Single",
              name: "hiddenInSingle",
              widget: "boolean",
              default: false,
            }
      - { label: "Body", name: "body", widget: "markdown" }
